# https://github.com/realm/SwiftLint

disabled_rules:
  - colon              # align properties
  - comma              # align func params
  - nesting            # nested constants

  - line_length        # nope

  - opening_brace      # if true { ... }
  - statement_position # else    { ... }
  
  - void_return        # () not Void

force_cast: warning

included:
  - Sources

excluded:
  - Sources/App/Assets
  