# https://github.com/realm/SwiftLint

disabled_rules:
  - colon                   # align properties
  - comma                   # align func params
  - return_arrow_whitespace # align return type

  - nesting            # nested constants
  - identifier_name    # id

  - line_length        # nope

  - opening_brace      # if true { ... }
  - statement_position # else    { ... }
  
  - void_return        # prefer () to Void

force_cast: warning

included:
  - Sources
  - Tests
