fastlane_version "2.64.0"

default_platform :ios

# desc "Runs all the tests"
# lane :test do
#   scan
# end

desc "Regenerate Localizable.swift file"
lane :translate do
  sh "python actions/create_localizations.py ../Sources/App"
end

desc "Creates new app screenshots"
lane :screenshot do
  snapshot
  # frameit
end

# desc "Submit a new Beta Build to Apple TestFlight"
# desc "This will also make sure the profile is up to date"
# lane :beta do
#   # match(type: "appstore") # more information: https://codesigning.guide
#   gym # Build your app - more options available
#   pilot

#   # sh "your_script.sh"
#   # You can also use other beta testing services here (run `fastlane actions`)
# end

# desc "Deploy a new version to the App Store"
# lane :release do
#   # match(type: "appstore")
#   # snapshot
#   gym # Build your app - more options available
#   deliver(force: true)
#   # frameit
# end

after_all do |lane|
  notification(subtitle: nil, message: "Finished line '#{lane}'.")
end

error do |lane, exception|
  notification(subtitle: nil, message: "Error when executing line '#{lane}'.")
end
